### Create credentials
POST http://localhost:9003/user
Content-Type: application/json

{
  "password": "teterster",
  "email": "testgter",
  "birthDate": "2007-12-03",
  "firstname": "aggzertyy",
  "lastname": "abhgzerty",
  "admin_flag": false
}

### Connect user
POST http://localhost:9003//authentication/connect
Content-Type: application/json

{
  "email": "tester",
  "password": "tester"
}
> {% client.global.set("token", response.body) %}

### Update user
PUT http://localhost:9003/user/test
Content-Type: application/json
Authorization: {{token}}

{
  "password": "tester",
  "email": "tester",
  "birthDate": "2009-12-03",
  "firstname": "mplo",
  "lastname": "olpm"
}


### get all users
GET http://localhost:9003/users